# Initializes the "build and deploy" workflow to have access to github secrets in that workflow
name: Init

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Init
        run: |
          echo "Initialized"
